name: 'Issue Templateless Parser'
description:
  'A GitHub Action that parses the body of an issue for output variables,
  without an issue template file'
author: 'benlei'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'play'
  color: 'red'

# Define your inputs here.
inputs:
  repository:
    description:
      'The repository to fetch the issue body from. For example,
      benlei/test-action'
    default: ${{ github.repository }}
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  issue-number:
    description: 'The number of the issue to get the body from'
    required: false
  issue-title:
    description:
      'The exact title of the issue to get the body from, if issue-number is not
      specified'
    required: false
  body:
    description: 'The body to parse for output variables'
    required: false
  fail-on-error:
    description: 'Whether to fail the action if any error occurs'
    default: 'true'
    required: false

# Define your outputs here.
outputs:
  generic: # output will be available to future steps
    description:
      'This command will have generic output variables based the issue body'
  issue-number:
    description: 'The issue number that was found, if it was found'

runs:
  using: node20
  main: dist/index.js
