name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action-body:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action - Body
        id: test
        uses: ./
        env:
          ISSUE_BODY: |
            ### Issue Title

            This is the body of the issue

            ```yaml
            time: 10
            ```

            And that's about it

            ### Something Else 123

            1235768457246

            ### Third Heading over here...

            Hello World
        with:
          body: ${{ env.ISSUE_BODY }}

      - name: Outputs are not correct
        if: |
          steps.test.outputs.issue-number != '' ||
          !contains(steps.test.outputs.issue-title, 'time: 10') ||
          !contains(steps.test.outputs.issue-title, 'about it') ||
          steps.test.outputs.something-else-123 != '1235768457246' ||
          steps.test.outputs.third-heading-over-here != 'Hello World'
        run: exit 1

  test-action-issue-number:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action - Issue Number
        id: test
        uses: ./
        with:
          issue-number: 3

      - name: Outputs are not correct
        if: |
          steps.test.outputs.issue-number != '3' ||
          !contains(steps.test.outputs.issue-title, 'time: 10') ||
          !contains(steps.test.outputs.issue-title, 'about it') ||
          steps.test.outputs.something-else-123 != '1235768457246' ||
          steps.test.outputs.third-heading-over-here != 'Hello World'
        run: exit 1

  test-action-issue-title:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action - Issue Title
        id: test
        uses: ./
        with:
          issue-title: Issue with example contents

      - name: Outputs are not correct
        if: |
          steps.test.outputs.issue-number != '3' ||
          !contains(steps.test.outputs.issue-title, 'time: 10') ||
          !contains(steps.test.outputs.issue-title, 'about it') ||
          steps.test.outputs.something-else-123 != '1235768457246' ||
          steps.test.outputs.third-heading-over-here != 'Hello World'
        run: exit 1
